version: '3.7'
      
services:
  redis:
    image: redis:5.0.8-alpine
    container_name: redis
    restart: always
    command: --requirepass 123456 --appendonly yes
    ports:
      - 6379:6379
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis_data:/data
    networks:
        nrsoft:
        
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=App1234#
      - TZ=Asia/Shanghai
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - nrsoft
      
      
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "40590:9000"
    privileged: true
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=App123456
      - TZ=Asia/Shanghai
    volumes: 
      - "./minio_data:/data"
    command: server /data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    networks:
      - nrsoft   
    
networks:
    nrsoft:
        external: true
      
      
      
